# Traditional Chinese message translation file for plpython
# Copyright (C) 2011 PostgreSQL Global Development Group
# This file is distributed under the same license as the PostgreSQL package.
# Zhenbang Wei <znbang@gmail.com>, 2011.
#
msgid ""
msgstr ""
"Project-Id-Version: PostgreSQL 9.1\n"
"Report-Msgid-Bugs-To: pgsql-bugs@postgresql.org\n"
"POT-Creation-Date: 2011-05-13 20:38+0000\n"
"PO-Revision-Date: 2011-05-12 16:09+0800\n"
"Last-Translator: Zhenbang Wei <znbang@gmail.com>\n"
"Language-Team: Traditional Chinese\n"
"Language: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: plpython.c:475
#, c-format
msgid "PL/Python function \"%s\""
msgstr "PL/Python 函式 \"%s\""

#: plpython.c:482
msgid "PL/Python anonymous code block"
msgstr "PL/Python 匿名程式塊"

#: plpython.c:489
msgid "while modifying trigger row"
msgstr "修改觸發程序行時"

#: plpython.c:496
msgid "while creating return value"
msgstr "建立傳回值時"

#: plpython.c:707 plpython.c:733
msgid "unexpected return value from trigger procedure"
msgstr "非預期的觸發程序傳回值"

#: plpython.c:708
msgid "Expected None or a string."
msgstr "預期 None 或字串"

#: plpython.c:723
msgid ""
"PL/Python trigger function returned \"MODIFY\" in a DELETE trigger -- ignored"
msgstr "DELETE 觸發的 PL/Python 觸發函式傳回 \"MODIFY\" -- 已忽略"

#: plpython.c:734
msgid "Expected None, \"OK\", \"SKIP\", or \"MODIFY\"."
msgstr "預期 None, \"OK\", \"SKIP\", 或 \"MODIFY\"。"

#: plpython.c:786
msgid "TD[\"new\"] deleted, cannot modify row"
msgstr "TD[\"new\"] 已刪除，無法修改資料行"

#: plpython.c:789
msgid "TD[\"new\"] is not a dictionary"
msgstr "TD[\"new\"] 不是字典"

#: plpython.c:813
#, c-format
msgid "TD[\"new\"] dictionary key at ordinal position %d is not a string"
msgstr "位置 %d 的 TD[\"new\"] 字典鍵值不是字串"

#: plpython.c:819
#, c-format
msgid ""
"key \"%s\" found in TD[\"new\"] does not exist as a column in the triggering "
"row"
msgstr "TD[\"new\"] 中的鍵值 \"%s\" 不在觸發資料行的欄位中"

#: plpython.c:915
msgid "could not create new dictionary while building trigger arguments"
msgstr "建立觸發程序參數時無法建立新字典"

#: plpython.c:1122
msgid "unsupported set function return mode"
msgstr "不支援設定函式回傳模式"

#: plpython.c:1123
msgid ""
"PL/Python set-returning functions only support returning only value per call."
msgstr ""

#: plpython.c:1135
msgid "returned object cannot be iterated"
msgstr "不能 iterate 傳回的物件"

#: plpython.c:1136
msgid "PL/Python set-returning functions must return an iterable object."
msgstr ""

#: plpython.c:1161
msgid "error fetching next item from iterator"
msgstr "從迭代器取下一個項目時發生錯誤"

#: plpython.c:1196
msgid "PL/Python function with return type \"void\" did not return None"
msgstr "傳回型別是 \"void\" 的 PL/Python 函式沒有傳回 None"

#: plpython.c:1287
msgid "forcibly aborting a subtransaction that has not been exited"
msgstr ""

#: plpython.c:1403
msgid "PyList_SetItem() failed, while setting up arguments"
msgstr "設定 PyList_SetItem() 的參數時失敗"

#: plpython.c:1407
msgid "PyDict_SetItemString() failed, while setting up arguments"
msgstr "設定 PyDict_SetItemString() 的參數時失敗"

#: plpython.c:1419
msgid ""
"function returning record called in context that cannot accept type record"
msgstr "在不接受型別紀錄的 context 中呼叫傳回紀錄的函式"

#: plpython.c:1633
msgid "trigger functions can only be called as triggers"
msgstr "觸發函式只能當做觸發程序呼叫"

#: plpython.c:1638 plpython.c:2089
#, c-format
msgid "PL/Python functions cannot return type %s"
msgstr "PL/Python 函式不能傳回型別 %s"

#: plpython.c:1721
#, c-format
msgid "PL/Python functions cannot accept type %s"
msgstr "PL/Python 函式不能接受型別 %s"

#: plpython.c:1817
#, c-format
msgid "could not compile PL/Python function \"%s\""
msgstr "無法編譯 PL/Python 函式 \"%s\""

#: plpython.c:1820
msgid "could not compile anonymous PL/Python code block"
msgstr "無法編譯 PL/Python 匿名程式塊"

#: plpython.c:2091
msgid "PL/Python does not support conversion to arrays of row types."
msgstr ""

#: plpython.c:2300
msgid "cannot convert multidimensional array to Python list"
msgstr "無法將多維陣列轉成 Python list"

#: plpython.c:2301
msgid "PL/Python only supports one-dimensional arrays."
msgstr "PL/Python 只支援一維陣列"

#: plpython.c:2340
msgid "could not create new dictionary"
msgstr "無法建立新字典"

#: plpython.c:2435
msgid "could not create bytes representation of Python object"
msgstr "無法建立 Python 物件的二進位表達格式"

#: plpython.c:2533
msgid "could not create string representation of Python object"
msgstr "無法建立 Python 物件的字串表達格式"

#: plpython.c:2544
msgid ""
"could not convert Python object into cstring: Python string representation "
"appears to contain null bytes"
msgstr ""

#: plpython.c:2578
msgid ""
"return value of function with array return type is not a Python sequence"
msgstr "傳回型別是陣列函式的傳回值不是 Python sequence"

#: plpython.c:2654
#, c-format
msgid "key \"%s\" not found in mapping"
msgstr "對照表中找不到鍵值 \"%s\""

#: plpython.c:2655
msgid ""
"To return null in a column, add the value None to the mapping with the key "
"named after the column."
msgstr "要傳回 null 欄位，以欄位名稱為鍵值將 None 加入對照表"

#: plpython.c:2703
msgid "length of returned sequence did not match number of columns in row"
msgstr "傳回的 sequence 長度和資料行欄位數量不符"

#: plpython.c:2803
#, c-format
msgid "attribute \"%s\" does not exist in Python object"
msgstr "屬性 \"%s\" 不存在於 Python 物件"

#: plpython.c:2804
msgid ""
"To return null in a column, let the returned object have an attribute named "
"after column with value None."
msgstr "要傳回 null 欄位，以欄位名稱為被傳回物件的屬性並以 None 為值"

#: plpython.c:3123
msgid "plan.status takes no arguments"
msgstr "plan.status 不接受參數"

#: plpython.c:3247
msgid "second argument of plpy.prepare must be a sequence"
msgstr "plpy.prepare 第二個參數必須是 sequence"

#: plpython.c:3297
#, c-format
msgid "plpy.prepare: type name at ordinal position %d is not a string"
msgstr "plpy.prepare: 位置 %d 的型別名稱不是字串"

#: plpython.c:3329
msgid "plpy.prepare does not support composite types"
msgstr "plpy.prepare 不支援複合型別"

#: plpython.c:3419
msgid "plpy.execute expected a query or a plan"
msgstr "plpy.execute 預期一個查詢或計畫"

#: plpython.c:3438
msgid "plpy.execute takes a sequence as its second argument"
msgstr "plpy.execute 接受 sequence 做為第二個參數"

#: plpython.c:3454
msgid "could not execute plan"
msgstr "無法執行計畫"

#: plpython.c:3457
#, c-format
msgid "Expected sequence of %d argument, got %d: %s"
msgid_plural "Expected sequence of %d arguments, got %d: %s"
msgstr[0] "預期 %d 個參數，收到 %d 個: %s"

#: plpython.c:3599
#, c-format
msgid "SPI_execute_plan failed: %s"
msgstr "SPI_execute_plan 失敗: %s"

#: plpython.c:3677
#, c-format
msgid "SPI_execute failed: %s"
msgstr "SPI_execute 失敗: %s"

#: plpython.c:3732
msgid "unrecognized error in PLy_spi_execute_fetch_result"
msgstr "PLy_spi_execute_fetch_result 有非預期錯誤"

#: plpython.c:3794
msgid "this subtransaction has already been entered"
msgstr ""

#: plpython.c:3800 plpython.c:3852
msgid "this subtransaction has already been exited"
msgstr ""

#: plpython.c:3846
msgid "this subtransaction has not been entered"
msgstr ""

#: plpython.c:3858
msgid "there is no subtransaction to exit from"
msgstr ""

#: plpython.c:3940
msgid "failed to add the spiexceptions module"
msgstr "新增 spiexceptions 模式失敗"

#: plpython.c:4017
msgid "Python major version mismatch in session"
msgstr "Python 主版號和 session 不符"

#: plpython.c:4018
#, c-format
msgid ""
"This session has previously used Python major version %d, and it is now "
"attempting to use Python major version %d."
msgstr "session 原來用 Python 主版號 %d，現在嘗試用 Python 主版號 %d。"

#: plpython.c:4020
msgid "Start a new session to use a different Python major version."
msgstr "用不同 Python 主版號開始新 session"

#: plpython.c:4035
msgid "untrapped error in initialization"
msgstr "初始化時有錯誤未被補捉"

#: plpython.c:4063
msgid "could not import \"__main__\" module"
msgstr "無法匯入 \"__main__\" 模組"

#: plpython.c:4070
msgid "could not initialize globals"
msgstr "無法初始化全域變數"

#: plpython.c:4183
msgid "could not parse error message in plpy.elog"
msgstr "無法解讀 plpy.elog 中的錯誤訊息"

# commands/vacuum.c:2258 commands/vacuumlazy.c:489 commands/vacuumlazy.c:770
# nodes/print.c:86 storage/lmgr/deadlock.c:888 tcop/postgres.c:3285
#: plpython.c:4207 plpython.c:4437 plpython.c:4438 plpython.c:4439
#: plpython.c:4440
#, c-format
msgid "%s"
msgstr "%s"

#: plpython.c:4791
msgid "could not convert Python Unicode object to PostgreSQL server encoding"
msgstr "無法將 Python Unicode 物件轉成 PostgreSQL 伺服器編碼"
